class Item {
  // itemId: GBF in-game item id (from supplies-response.json), used to build the
  // akamaized item-image URL in WikiParser/data/supplies.images. Null for the 4
  // animated (.gif) generic icons and the 30 weapon-namespace items (rusted /
  // silver relic / revenant), which have no item/article id and keep gbf.wiki.
  constructor(name, category, itemId = null, animated = false) {
    this.name = name;
    this.category = category;
    this.itemId = itemId;
    this.animated = animated;
  }
};

const Categories = Object.freeze({
  quest: 100,
  coop: 200,
  anima: 300,
  arcarum: 400,
});

const items = Object.freeze({
  rupie: new Item('Rupie', Categories.quest, 'lupi'),
  crystal: new Item('Crystal', Categories.quest, 'gem'),
  blueskycristal: new Item('Blue Sky Crystal', Categories.quest, '1'),
  satinfeather: new Item('Satin Feather', Categories.quest, '2'),
  untamedflame: new Item('Untamed Flame', Categories.quest, '5'),
  roughstone: new Item('Rough Stone', Categories.quest, '8'),
  freshwaterjug: new Item('Fresh Water Jug', Categories.quest, '6'),
  vermilionstone: new Item('Vermilion Stone', Categories.quest, '24'),
  hollowsoul: new Item('Hollow Soul', Categories.quest, '28'),
  zephyrfeather: new Item('Zephyr Feather', Categories.quest, '3'),
  falconfeather: new Item('Falcon Feather', Categories.quest, '22'),
  forebodingclover: new Item('Foreboding Clover', Categories.quest, '39'),
  swirlingamber: new Item('Swirling Amber', Categories.quest, '17'),
  lacrimosa: new Item('Lacrimosa', Categories.quest, '29'),
  bloodamber: new Item('Blood Amber', Categories.quest, '40'),
  antiquecloth: new Item('Antique Cloth', Categories.quest, '54'),
  goldbrick: new Item('Gold Brick', Categories.quest, '20004'),
  damascuscrystal: new Item('Damascus Crystal', Categories.quest, '203'),
  brightspirits: new Item('Bright Spirits', Categories.quest, '80'),
  murkyspirits: new Item('Murky Spirits', Categories.quest, '81'),
  blueskyspirit: new Item('Blue-Sky Spirit', Categories.quest, '6510'),
  truedragonsgoldenscale: new Item('True Dragon\'s Golden Scale', Categories.quest, '547'),
  tearsoftheapocalypse: new Item('Tears of the Apocalypse', Categories.quest, '538'),
  abyssalwing: new Item('Abyssal Wing', Categories.quest, '555'),
  cunningdevilshorn: new Item('Cunning Devil\'s Horn', Categories.quest, '570'),
  eternitysand: new Item('Eternity Sand', Categories.quest, '215'),
  terraadamant: new Item('Terra Adamant', Categories.quest, '6513'),
  //: new Item('', Categories.quest),
  flawlessprism: new Item('Flawless Prism', Categories.quest, '1203'),
  flawedprism: new Item('Flawed Prism', Categories.quest, '1202'),
  rainbowprism: new Item('Rainbow Prism', Categories.quest, '1204'),
  championmerit: new Item('Champion Merit', Categories.quest, '2001'),
  suprememerit: new Item('Supreme Merit', Categories.quest, '2002'),
  legendarymerit: new Item('Legendary Merit', Categories.quest, '2003'),
  lapismerit: new Item('Lapis Merit', Categories.quest, '6511'),
  silvercentrum: new Item('Silver Centrum', Categories.quest, '107'),
  sunlightstone: new Item('Sunlight Stone', Categories.quest, '20014'),
  genesisfragment: new Item('Genesis Fragment', Categories.quest, '535'),
  immortalfragment: new Item('Immortal Fragment', Categories.quest, '612'),
  primevalhorn: new Item('Primeval Horn', Categories.quest, '79'),
  malicefragment: new Item('Malice Fragment', Categories.quest, '533'),
  verdantazurite: new Item('Verdant Azurite', Categories.quest, '546'),
  sephirastone: new Item('Sephira Stone', Categories.arcarum, '25000'),
  sephiraevolite: new Item('Sephira Evolite', Categories.arcarum, '25036'),
  newworldquartz: new Item('New World Quartz', Categories.arcarum, '25074'),
  // Dragon Scales
  reddragonscale: new Item('Red Dragon Scale', Categories.quest, '1111'),
  bluedragonscale: new Item('Blue Dragon Scale', Categories.quest, '1121'),
  browndragonscale: new Item('Brown Dragon Scale', Categories.quest, '1131'),
  greendragonscale: new Item('Green Dragon Scale', Categories.quest, '1141'),
  whitedragonscale: new Item('White Dragon Scale', Categories.quest, '1151'),
  blackdragonscale: new Item('Black Dragon Scale', Categories.quest, '1161'),
  // High Orbs
  orbfire: new Item('Inferno Orb', Categories.quest, '1012'),
  orbwater: new Item('Frost Orb', Categories.quest, '1022'),
  orbearth: new Item('Rumbling Orb', Categories.quest, '1032'),
  orbwind: new Item('Cyclone Orb', Categories.quest, '1042'),
  orblight: new Item('Shining Orb', Categories.quest, '1052'),
  orbdark: new Item('Abysm Orb', Categories.quest, '1062'),
  // Low Orbs
  loworbfire: new Item('Fire Orb', Categories.quest, '1011'),
  loworbwater: new Item('Water Orb', Categories.quest, '1021'),
  loworbearth: new Item('Earth Orb', Categories.quest, '1031'),
  loworbwind: new Item('Wind Orb', Categories.quest, '1041'),
  loworblight: new Item('Light Orb', Categories.quest, '1051'),
  loworbdark: new Item('Dark Orb', Categories.quest, '1061'),
  loworb: new Item('Low Orb', Categories.quest, null, true),
  // Scrolls
  scrollfire: new Item('Hellfire Scroll', Categories.quest, '1312'),
  scrollwater: new Item('Flood Scroll', Categories.quest, '1322'),
  scrollearth: new Item('Thunder Scroll', Categories.quest, '1332'),
  scrollwind: new Item('Gale Scroll', Categories.quest, '1342'),
  scrolllight: new Item('Skylight Scroll', Categories.quest, '1352'),
  scrolldark: new Item('Chasm Scroll', Categories.quest, '1362'),
  // Tomes
  tomefire: new Item('Red Tome', Categories.quest, '1311'),
  tomewater: new Item('Blue Tome', Categories.quest, '1321'),
  tomeearth: new Item('Brown Tome', Categories.quest, '1331'),
  tomewind: new Item('Green Tome', Categories.quest, '1341'),
  tomelight: new Item('White Tome', Categories.quest, '1351'),
  tomedark: new Item('Black Tome', Categories.quest, '1361'),
  // Grimoires
  firegrimoire: new Item('Fire Grimoire', Categories.quest, '20711'),
  watergrimoire: new Item('Water Grimoire', Categories.quest, '20721'),
  earthgrimoire: new Item('Earth Grimoire', Categories.quest, '20731'),
  windgrimoire: new Item('Wind Grimoire', Categories.quest, '20741'),
  // True Anima
  trueanimafire: new Item('True Fire Anima', Categories.quest, '41'),
  trueanimawater: new Item('True Water Anima', Categories.quest, '42'),
  trueanimaearth: new Item('True Earth Anima', Categories.quest, '43'),
  trueanimawind: new Item('True Wind Anima', Categories.quest, '44'),
  trueanimalight: new Item('True Light Anima', Categories.quest, '45'),
  trueanimadark: new Item('True Dark Anima', Categories.quest, '46'),
  trueanima: new Item('True Anima', Categories.quest, null, true),
  // Whorls
  whorlfire: new Item('Infernal Whorl', Categories.quest, '1313'),
  whorlwater: new Item('Tidal Whorl', Categories.quest, '1323'),
  whorlearth: new Item('Seismic Whorl', Categories.quest, '1333'),
  whorlwind: new Item('Tempest Whorl', Categories.quest, '1343'),
  whorllight: new Item('Radiant Whorl', Categories.quest, '1353'),
  whorldark: new Item('Umbral Whorl', Categories.quest, '1363'),
  whorl: new Item('Whorl', Categories.quest, null, true),
  // Centrums
  rubeuscentrum: new Item('Rubeus Centrum', Categories.quest, '101'),
  indicuscentrum: new Item('Indicus Centrum', Categories.quest, '102'),
  luteuscentrum: new Item('Luteus Centrum', Categories.quest, '103'),
  galbinuscentrum: new Item('Galbinus Centrum', Categories.quest, '104'),
  niveuscentrum: new Item('Niveus Centrum', Categories.quest, '105'),
  atercentrum: new Item('Ater Centrum', Categories.quest, '106'),
  // Treasures
  toxictulip: new Item('Toxic Tulip', Categories.quest, '130'),
  bestiafruit: new Item('Bestia Fruit', Categories.quest, '129'),
  jumbobeastbone: new Item('Jumbo Beast Bone', Categories.quest, '128'),
  klugerherb: new Item('Kluger Herb', Categories.quest, '126'),
  rhempepper: new Item('Rhem Pepper', Categories.quest, '144'),
  brokenteacup: new Item('Broken Teacup', Categories.quest, '148'),
  rustyeave: new Item('Rusty Eave', Categories.quest, '145'),
  translucentsilk: new Item('Translucent Silk', Categories.quest, '146'),
  meditativesutra: new Item('Meditative Sutra', Categories.quest, '127'),
  dustybook: new Item('Dusty Book', Categories.quest, '147'),
  // Co-op Rotating Showdown Item
  infernalgarnet: new Item('Infernal Garnet', Categories.coop, '20611'),
  frozenhellprism: new Item('Frozen Hell Prism', Categories.coop, '20621'),
  eviljudgecrystal: new Item('Evil Judge Crystal', Categories.coop, '20631'),
  horsemansplate: new Item('Horseman\'s Plate', Categories.coop, '20641'),
  halolightquartz: new Item('Halo Light Quartz', Categories.coop, '20651'),
  phantomdemonjewel: new Item('Phantom Demon Jewel', Categories.coop, '20661'),
  // Class distinctions
  guardiandistinction: new Item('Guardian Distinction', Categories.coop, '20421'),
  sharpshooterdistinction: new Item('Sharpshooter Distinction', Categories.coop, '20481'),
  gladiatordistinction: new Item('Gladiator Distinction', Categories.coop, '20411'),
  fencerdistinction: new Item('Fencer Distinction', Categories.coop, '20461'),
  pilgrimdistinction: new Item('Pilgrim Distinction', Categories.coop, '20431'),
  combatantdistinction: new Item('Combatant Distinction', Categories.coop, '20471'),
  swordmasterdistinction: new Item('Sword Master Distinction', Categories.coop, '20691'),
  samuraidistinction: new Item('Samurai Distinction', Categories.coop, '20671'),
  troubadourdistinction: new Item('Troubadour Distinction', Categories.coop, '20491'),
  banditdistinction: new Item('Bandit Distinction', Categories.coop, '20451'),
  // Elemental Quartz
  firequartz: new Item('Fire Quartz', Categories.quest, '5011'),
  waterquartz: new Item('Water Quartz', Categories.quest, '5021'),
  earthquartz: new Item('Earth Quartz', Categories.quest, '5031'),
  windquartz: new Item('Wind Quartz', Categories.quest, '5041'),
  lightquartz: new Item('Light Quartz', Categories.quest, '5051'),
  darkquartz: new Item('Dark Quartz', Categories.quest, '5061'),
  // Trial Fragment
  hellfirefragment: new Item('Hellfire Fragment', Categories.quest, '5111'),
  delugefragment: new Item('Deluge Fragment', Categories.quest, '5121'),
  wastelandfragment: new Item('Wasteland Fragment', Categories.quest, '5131'),
  typhoonfragment: new Item('Typhoon Fragment', Categories.quest, '5141'),
  // Urn
  fireurn: new Item('Fire Urn', Categories.quest, '111'),
  waterurn: new Item('Water Urn', Categories.quest, '112'),
  earthurn: new Item('Earth Urn', Categories.quest, '113'),
  windurn: new Item('Wind Urn', Categories.quest, '114'),
  lighturn: new Item('Light Urn', Categories.quest, '115'),
  darkurn: new Item('Dark Urn', Categories.quest, '116'),
  // Weapon Stones
  stoneaxe: new Item('Axe Stone', Categories.quest, '4041'),
  stonebow: new Item('Bow Stone', Categories.quest, '4081'),
  stonedagger: new Item('Dagger Stone', Categories.quest, '4021'),
  stonegauntlet: new Item('Melee Stone', Categories.quest, '4071'),
  stonegun: new Item('Pistol Stone', Categories.quest, '4061'),
  stoneharp: new Item('Harp Stone', Categories.quest, '4091'),
  stonekatana: new Item('Katana Stone', Categories.quest, '4101'),
  stonelance: new Item('Spear Stone', Categories.quest, '4031'),
  stonestaff: new Item('Staff Stone', Categories.quest, '4051'),
  stonesword: new Item('Sword Stone', Categories.quest, '4011'),
  // Rusted weapons
  rustedaxe: new Item('Rusted Axe', Categories.quest),
  rustedbow: new Item('Rusted Bow', Categories.quest),
  rusteddagger: new Item('Rusted Dagger', Categories.quest),
  rustedgauntlet: new Item('Rusted Gauntlet', Categories.quest),
  rustedgun: new Item('Rusted Gun', Categories.quest),
  rustedharp: new Item('Rusted Harp', Categories.quest),
  rustedkatana: new Item('Rusted Katana', Categories.quest),
  rustedlance: new Item('Rusted Lance', Categories.quest),
  rustedstaff: new Item('Rusted Staff', Categories.quest),
  rustedsword: new Item('Rusted Sword', Categories.quest),
  rustedweapon: new Item('Rusted Weapon', Categories.quest, null, true),
  // Silver Shards
  silvershardaxe: new Item('Silver Axe Shard', Categories.quest, '5441'),
  silvershardbow: new Item('Silver Bow Shard', Categories.quest, '5481'),
  silversharddagger: new Item('Silver Dagger Shard', Categories.quest, '5421'),
  silvershardgauntlet: new Item('Silver Gauntlet Shard', Categories.quest, '5471'),
  silvershardgun: new Item('Silver Gun Shard', Categories.quest, '5461'),
  silvershardharp: new Item('Silver Harp Shard', Categories.quest, '5491'),
  silvershardkatana: new Item('Silver Katana Shard', Categories.quest, '5501'),
  silvershardlance: new Item('Silver Spear Shard', Categories.quest, '5431'),
  silvershardstaff: new Item('Silver Staff Shard', Categories.quest, '5451'),
  silvershardsword: new Item('Silver Sword Shard', Categories.quest, '5411'),
  // Silver relics
  silveraxe: new Item('Silver Axe Relic', Categories.quest),
  silverbow: new Item('Silver Bow Relic', Categories.quest),
  silverdagger: new Item('Silver Dagger Relic', Categories.quest),
  silvergauntlet: new Item('Silver Gauntlet Relic', Categories.quest),
  silvergun: new Item('Silver Gun Relic', Categories.quest),
  silverharp: new Item('Silver Harp Relic', Categories.quest),
  silverkatana: new Item('Silver Katana Relic', Categories.quest),
  silverlance: new Item('Silver Spear Relic', Categories.quest),
  silverstaff: new Item('Silver Staff Relic', Categories.quest),
  silversword: new Item('Silver Sword Relic', Categories.quest),
  // Revenant weapons
  revenantw1: new Item('One-Rift Spear', Categories.quest),
  revenantw2: new Item('Two-Crown Bow', Categories.quest),
  revenantw3: new Item('Three-Tiger Axe', Categories.quest),
  revenantw4: new Item('Four-Sky Blade', Categories.quest),
  revenantw5: new Item('Five-Soul Staff', Categories.quest),
  revenantw6: new Item('Six-Ruin Fist', Categories.quest),
  revenantw7: new Item('Seven-Star Sword', Categories.quest),
  revenantw8: new Item('Eight-Life Katana', Categories.quest),
  revenantw9: new Item('Nine-Realm Harp', Categories.quest),
  revenantw10: new Item('Ten-Wolf Gun', Categories.quest),
  // Revenant Weapon Fragment
  wfragment1: new Item('One-Star Fragment', Categories.quest, '5611'),
  wfragment2: new Item('Two-Star Fragment', Categories.quest, '5621'),
  wfragment3: new Item('Three-Star Fragment', Categories.quest, '5631'),
  wfragment4: new Item('Four-Star Fragment', Categories.quest, '5641'),
  wfragment5: new Item('Five-Star Fragment', Categories.quest, '5651'),
  wfragment6: new Item('Six-Star Fragment', Categories.quest, '5661'),
  wfragment7: new Item('Seven-Star Fragment', Categories.quest, '5671'),
  wfragment8: new Item('Eight-Star Fragment', Categories.quest, '5681'),
  wfragment9: new Item('Nine-Star Fragment', Categories.quest, '5691'),
  wfragment10: new Item('Ten-Star Fragment', Categories.quest, '5701'),
  // Astra
	flameborneastra: new Item('Flameborne Astra', Categories.arcarum, '25001'),
	aquaborneastra: new Item('Aquaborne Astra', Categories.arcarum, '25002'),
  earthborneastra: new Item('Earthborne Astra', Categories.arcarum, '25003'),
  windborneastra: new Item('Windborne Astra', Categories.arcarum, '25004'),
  lightborneastra: new Item('Lightborne Astra', Categories.arcarum, '25005'),
  darkborneastra: new Item('Darkborne Astra', Categories.arcarum, '25006'),
  // Idean
	justiceidean: new Item('Justice Idean', Categories.arcarum, '25007'),
  hangedmanidean: new Item('Hanged Man Idean', Categories.arcarum, '25008'),
  deathidean: new Item('Death Idean', Categories.arcarum, '25009'),
  temperanceidean: new Item('Temperance Idean', Categories.arcarum, '25010'),
  devilidean: new Item('Devil Idean', Categories.arcarum, '25011'),
  toweridean: new Item('Tower Idean', Categories.arcarum, '25012'),
  staridean: new Item('Star Idean', Categories.arcarum, '25013'),
  moonidean: new Item('Moon Idean', Categories.arcarum, '25014'),
  sunidean: new Item('Sun Idean', Categories.arcarum, '25015'),
  judgementidean: new Item('Judgement Idean', Categories.arcarum, '25016'),
  worldidean: new Item('World Idean', Categories.arcarum, '25017'),
  // Veritas
	justiceveritas: new Item('Justice Veritas', Categories.arcarum, '25047'),
  hangedmanveritas: new Item('Hanged Man Veritas', Categories.arcarum, '25048'),
  deathveritas: new Item('Death Veritas', Categories.arcarum, '25049'),
  temperanceveritas: new Item('Temperance Veritas', Categories.arcarum, '25050'),
  devilveritas: new Item('Devil Veritas', Categories.arcarum, '25051'),
  towerveritas: new Item('Tower Veritas', Categories.arcarum, '25052'),
  starveritas: new Item('Star Veritas', Categories.arcarum, '25053'),
  moonveritas: new Item('Moon Veritas', Categories.arcarum, '25054'),
  sunveritas: new Item('Sun Veritas', Categories.arcarum, '25055'),
  judgementveritas: new Item('Judgement Veritas', Categories.arcarum, '25056'),
  // Verum
  fireverum: new Item('Fire Verum Proof', Categories.arcarum, '25023'),
  waterverum: new Item('Water Verum Proof', Categories.arcarum, '25024'),
  earthverum: new Item('Earth Verum Proof', Categories.arcarum, '25025'),
  windverum: new Item('Wind Verum Proof', Categories.arcarum, '25026'),
  // Luster
  fireluster: new Item('Ignis Luster', Categories.arcarum, '25070'),
  waterluster: new Item('Aqua Luster', Categories.arcarum, '25071'),
  earthluster: new Item('Terra Luster', Categories.arcarum, '25072'),
  windluster: new Item('Ventus Luster', Categories.arcarum, '25073'),
  // Haze
  aurorahaze: new Item('Aurora Haze', Categories.arcarum, '25020'),
  chaotichaze: new Item('Chaotic Haze', Categories.arcarum, '25021'),
  // Arcarum Fragment
  aquilafragment: new Item('Aquila Fragment', Categories.arcarum, '25033'),
  bellatorfragment: new Item('Bellator Fragment', Categories.arcarum, '25034'),
  celsusfragment: new Item('Celsus Fragment', Categories.arcarum, '25035'),
  // Gospel
  gospelofgenea: new Item('Gospel of Genea', Categories.arcarum, '25088'),
  gospelofegeiro: new Item('Gospel of Egeiro', Categories.arcarum, '25085'),
  gospelofthysia: new Item('Gospel of Thysia', Categories.arcarum, '25087'),
  gospelofanalipsis: new Item('Gospel of Analipsis', Categories.arcarum, '25086'),
  // Anima
  animafire: new Item('Colossus Anima', Categories.anima, '11'),
  animawater: new Item('Leviathan Anima', Categories.anima, '12'),
  animaearth: new Item('Yggdrasil Anima', Categories.anima, '13'),
  animawind: new Item('Tiamat Anima', Categories.anima, '10'),
  animalight: new Item('Luminiera Anima', Categories.anima, '25'),
  animadark: new Item('Celeste Anima', Categories.anima, '30'),
  // Omega Anima
  fireomegaanima: new Item('Colossus Omega Anima', Categories.anima, '19'),
  wateromegaanima: new Item('Leviathan Omega Anima', Categories.anima, '20'),
  earthomegaanima: new Item('Yggdrasil Omega Anima', Categories.anima, '21'),
  windomegaanima: new Item('Tiamat Omega Anima', Categories.anima, '18'),
  lightomegaanima: new Item('Luminiera Omega Anima', Categories.anima, '26'),
  darkomegaanima: new Item('Celeste Omega Anima', Categories.anima, '31'),
  // Omega Unique items
  omegauniquefire: new Item('Resolute Reactor', Categories.anima, '47'),
  omegauniquewater: new Item('Fanned Fin', Categories.anima, '48'),
  omegauniqueearth: new Item('Genesis Bud', Categories.anima, '49'),
  omegauniquewind: new Item('Green Dragon Eye', Categories.anima, '32'),
  omegauniquelight: new Item('Primal Bit', Categories.anima, '50'),
  omegauniquedark: new Item('Black Fog Sphere', Categories.anima, '51'),
  // Omega 2 Omega Anima
  fireomega2omegaanima: new Item('Shiva Omega Anima', Categories.anima, '511'),
  wateromega2omegaanima: new Item('Europa Omega Anima', Categories.anima, '513'),
  earthomega2omegaanima: new Item('Alexiel Omega Anima', Categories.anima, '515'),
  windomega2omegaanima: new Item('Grimnir Omega Anima', Categories.anima, '517'),
  lightomega2omegaanima: new Item('Metatron Omega Anima', Categories.anima, '519'),
  darkomega2omegaanima: new Item('Avatar Omega Anima', Categories.anima, '521'),
  // Ennead Omega Anima
  fireenneadomegaanima: new Item('Atum Omega Anima', Categories.anima, '576'),
  waterenneadomegaanima: new Item('Tefnut Omega Anima', Categories.anima, '578'),
  earthenneadomegaanima: new Item('Bennu Omega Anima', Categories.anima, '580'),
  windenneadomegaanima: new Item('Ra Omega Anima', Categories.anima, '582'),
  lightenneadomegaanima: new Item('Horus Omega Anima', Categories.anima, '583'),
  darkenneadomegaanima: new Item('Osiris Omega Anima', Categories.anima, '584'),
  // Omega 3 Omega Anima
  fireomega3omegaanima: new Item('Ira Omega Anima', Categories.anima, '603'),
  wateromega3omegaanima: new Item('Mare Omega Anima', Categories.anima, '605'),
  earthomega3omegaanima: new Item('Arbos Omega Anima', Categories.anima, '607'),
  windomega3omegaanima: new Item('Aura Omega Anima', Categories.anima, '601'),
  lightomega3omegaanima: new Item('Credo Omega Anima', Categories.anima, '609'),
  darkomega3omegaanima: new Item('Ater Omega Anima', Categories.anima, '611'),
  // Six-Dragon Advent
  firesixdragon: new Item('Smoldering Rubble', Categories.anima, '549'),
  watersixdragon: new Item('Abyssal Tragedy', Categories.anima, '550'),
  earthsixdragon: new Item('Insular Core', Categories.anima, '551'),
  windsixdragon: new Item('Gale Rock', Categories.anima, '552'),
  lightsixdragon: new Item('Thunderbolt Wheel', Categories.anima, '553'),
  darksixdragon: new Item('Todestrieb', Categories.anima, '554'),
  // Six-Dragon Jewels
  firesixdragonjewel: new Item('Wilnas\'s Jewel', Categories.anima, '557'),
  watersixdragonjewel: new Item('Wamdus\'s Jewel', Categories.anima, '558'),
  earthsixdragonjewel: new Item('Galleon\'s Jewel', Categories.anima, '559'),
  windsixdragonjewel: new Item('Ewiyar\'s Jewel', Categories.anima, '560'),
  lightsixdragonjewel: new Item('Lu Woh\'s Jewel', Categories.anima, '561'),
  darksixdragonjewel: new Item('Fediel\'s Jewel', Categories.anima, '562'),
  // Tier 1 Summon Anima
  firet1anima: new Item('Twin Elements Anima', Categories.anima, '64'),
  watert1anima: new Item('Macula Marius Anima', Categories.anima, '60'),
  eartht1anima: new Item('Medusa Anima', Categories.anima, '62'),
  windt1anima: new Item('Nezha Anima', Categories.anima, '65'),
  lightt1anima: new Item('Apollo Anima', Categories.anima, '66'),
  darkt1anima: new Item('Dark Angel Olivia Anima', Categories.anima, '63'),
  // Tier 2 Summon Anima
  firet2anima: new Item('Athena Anima', Categories.anima, '85'),
  watert2anima: new Item('Grani Anima', Categories.anima, '68'),
  eartht2anima: new Item('Baal Anima', Categories.anima, '87'),
  windt2anima: new Item('Garuda Anima', Categories.anima, '92'),
  lightt2anima: new Item('Odin Anima', Categories.anima, '67'),
  darkt2anima: new Item('Lich Anima', Categories.anima, '72'),
  // Primarch Anima
  michaelanima: new Item('Michael Anima', Categories.anima, '506'),
  gabrielanima: new Item('Gabriel Anima', Categories.anima, '507'),
  urielanima: new Item('Uriel Anima', Categories.anima, '508'),
  raphaelanima: new Item('Raphael Anima', Categories.anima, '509'),
  // Halo
  halofire: new Item('Fire Halo', Categories.anima, '5211'),
  halowater: new Item('Water Halo', Categories.anima, '5221'),
  haloearth: new Item('Earth Halo', Categories.anima, '5231'),
  halowind: new Item('Wind Halo', Categories.anima, '5241'),
  // Sacred beasts Omega Anima
  huanglongomegaanima: new Item('Huanglong Omega Anima', Categories.anima, '529'),
  qilinomegaanima: new Item('Qilin Omega Anima', Categories.anima, '531'),
});

const GroupType = Object.freeze({
  element: "element",
  summon: "summon",
});

const groups = Object.freeze({
  quartz: {
		type: GroupType.element,
    fire: 'firequartz',
    water: 'waterquartz',
    earth: 'earthquartz',
    wind: 'windquartz',
    light: 'lightquartz',
    dark: 'darkquartz'
  },
  trialfragment: {
    type: GroupType.element,
    fire: 'hellfirefragment',
    water: 'delugefragment',
    earth: 'wastelandfragment',
    wind: 'typhoonfragment',
    light: ['hellfirefragment', 'typhoonfragment'],
    dark: ['delugefragment', 'wastelandfragment']
  },
  dragonscale: {
		type: GroupType.element,
    fire: 'reddragonscale',
    water: 'bluedragonscale',
    earth: 'browndragonscale',
    wind: 'greendragonscale',
    light: 'whitedragonscale',
    dark: 'blackdragonscale'
  },
  urns: {
    type: GroupType.element,
    fire: 'fireurn',
    water: 'waterurn',
    earth: 'earthurn',
    wind: 'windurn',
    light: 'lighturn',
    dark: 'darkurn'
  },
  orbs: {
    type: GroupType.element,
    fire: 'orbfire',
    water: 'orbwater',
    earth: 'orbearth',
    wind: 'orbwind',
    light: 'orblight',
    dark: 'orbdark',
  },
  loworbs: {
    type: GroupType.element,
    fire: 'loworbfire',
    water: 'loworbwater',
    earth: 'loworbearth',
    wind: 'loworbwind',
    light: 'loworblight',
    dark: 'loworbdark',
  },
  scrolls: {
    type: GroupType.element,
    fire: 'scrollfire',
    water: 'scrollwater',
    earth: 'scrollearth',
    wind: 'scrollwind',
    light: 'scrolllight',
    dark: 'scrolldark',
  },
  tomes: {
    type: GroupType.element,
    fire: 'tomefire',
    water: 'tomewater',
    earth: 'tomeearth',
    wind: 'tomewind',
    light: 'tomelight',
    dark: 'tomedark',
  },
  grimoires: {
    type: GroupType.element,
    fire: 'firegrimoire',
    water: 'watergrimoire',
    earth: 'earthgrimoire',
    wind: 'windgrimoire',
    light: ['firegrimoire', 'windgrimoire'],
    dark: ['watergrimoire', 'earthgrimoire']
  },
  spirits: {
    type: GroupType.element,
    fire: 'brightspirits',
    water: 'murkyspirits',
    earth: 'murkyspirits',
    wind: 'brightspirits',
    light: 'brightspirits',
    dark: 'murkyspirits',
  },
  trueanimas: {
    type: GroupType.element,
    fire: 'trueanimafire',
    water: 'trueanimawater',
    earth: 'trueanimaearth',
    wind: 'trueanimawind',
    light: 'trueanimalight',
    dark: 'trueanimadark',
  },
  whorls: {
    type: GroupType.element,
    fire: 'whorlfire',
    water: 'whorlwater',
    earth: 'whorlearth',
    wind: 'whorlwind',
    light: 'whorllight',
    dark: 'whorldark',
  },
  centrums: {
    type: GroupType.element,
    fire: 'rubeuscentrum',
    water: 'indicuscentrum',
    earth: 'luteuscentrum',
    wind: 'galbinuscentrum',
    light: 'niveuscentrum',
    dark: 'atercentrum',
  },
  weaponstones: {
    type: GroupType.summon,
    3040030: 'stonelance',
    3040031: 'stonebow',
    3040032: 'stoneaxe',
    3040033: 'stonedagger',
    3040034: 'stonestaff',
    3040035: 'stonegauntlet',
    3040036: 'stonesword',
    3040037: 'stonekatana',
    3040038: 'stoneharp',
    3040039: 'stonegun',
  },
  rustedw: {
    type: GroupType.summon,
    3040030: 'rustedlance',
    3040031: 'rustedbow',
    3040032: 'rustedaxe',
    3040033: 'rusteddagger',
    3040034: 'rustedstaff',
    3040035: 'rustedgauntlet',
    3040036: 'rustedsword',
    3040037: 'rustedkatana',
    3040038: 'rustedharp',
    3040039: 'rustedgun',
  },
  silverw: {
    type: GroupType.summon,
    3040030: 'silverlance',
    3040031: 'silverbow',
    3040032: 'silveraxe',
    3040033: 'silverdagger',
    3040034: 'silverstaff',
    3040035: 'silvergauntlet',
    3040036: 'silversword',
    3040037: 'silverkatana',
    3040038: 'silverharp',
    3040039: 'silvergun',
  },
  silvershards: {
    type: GroupType.summon,
    3040030: 'silvershardlance',
    3040031: 'silvershardbow',
    3040032: 'silvershardaxe',
    3040033: 'silversharddagger',
    3040034: 'silvershardstaff',
    3040035: 'silvershardgauntlet',
    3040036: 'silvershardsword',
    3040037: 'silvershardkatana',
    3040038: 'silvershardharp',
    3040039: 'silvershardgun',
  },
  revenantw: {
    type: GroupType.summon,
    3040030: 'revenantw1',
    3040031: 'revenantw2',
    3040032: 'revenantw3',
    3040033: 'revenantw4',
    3040034: 'revenantw5',
    3040035: 'revenantw6',
    3040036: 'revenantw7',
    3040037: 'revenantw8',
    3040038: 'revenantw9',
    3040039: 'revenantw10',
  },
  wfragment: {
    type: GroupType.summon,
    3040030: 'wfragment1',
    3040031: 'wfragment2',
    3040032: 'wfragment3',
    3040033: 'wfragment4',
    3040034: 'wfragment5',
    3040035: 'wfragment6',
    3040036: 'wfragment7',
    3040037: 'wfragment8',
    3040038: 'wfragment9',
    3040039: 'wfragment10',
  },
  // Co-op
  coopshowdownitem: {
		type: GroupType.element,
    fire: 'infernalgarnet',
    water: 'frozenhellprism',
    earth: 'eviljudgecrystal',
    wind: 'horsemansplate',
    light: 'halolightquartz',
    dark: 'phantomdemonjewel'
  },
  distinctions: {
    type: GroupType.summon,
    3040030: 'guardiandistinction',
    3040031: 'sharpshooterdistinction',
    3040032: 'gladiatordistinction',
    3040033: 'fencerdistinction',
    3040034: 'pilgrimdistinction',
    3040035: 'combatantdistinction',
    3040036: 'swordmasterdistinction',
    3040037: 'samuraidistinction',
    3040038: 'troubadourdistinction',
    3040039: 'banditdistinction',
  },
  // Arcarum  
	astra: {
		type: GroupType.element,
    fire: 'flameborneastra',
    water: 'aquaborneastra',
    earth: 'earthborneastra',
    wind: 'windborneastra',
    light: 'lightborneastra',
    dark: 'darkborneastra'
	},
	idean: {
		type: GroupType.summon,
    2040236: 'justiceidean',
    2040237: 'hangedmanidean',
    2040238: 'deathidean',
    2040239: 'temperanceidean',
    2040240: 'devilidean',
    2040241: 'toweridean',
    2040242: 'staridean',
    2040243: 'moonidean',
    2040244: 'sunidean',
    2040245: 'judgementidean',    
  },
	veritas: {
		type: GroupType.summon,
    2040236: 'justiceveritas',
    2040237: 'hangedmanveritas',
    2040238: 'deathveritas',
    2040239: 'temperanceveritas',
    2040240: 'devilveritas',
    2040241: 'towerveritas',
    2040242: 'starveritas',
    2040243: 'moonveritas',
    2040244: 'sunveritas',
    2040245: 'judgementveritas',    
  },
  verum: {
    type: GroupType.element,
    fire: 'fireverum',
    water: 'waterverum',
    earth: 'earthverum',
    wind: 'windverum',
    light: ['fireverum', 'windverum'],
    dark: ['waterverum', 'earthverum']
  },
  luster: {
    type: GroupType.element,
    fire: 'fireluster',
    water: 'waterluster',
    earth: 'earthluster',
    wind: 'windluster',
    light: ['fireluster', 'windluster'],
    dark: ['waterluster', 'earthluster']
  },
  gospel: {
    type: GroupType.element,
    fire: 'gospelofegeiro',
    water: 'gospelofanalipsis',
    earth: 'gospelofthysia',
    wind: 'gospelofgenea',
    light: ['gospelofgenea', 'gospelofegeiro'],
    dark: ['gospelofanalipsis', 'gospelofthysia']
  },
  haze: {
		type: GroupType.element,
    fire: 'aurorahaze',
    water: 'chaotichaze',
    earth: 'chaotichaze',
    wind: 'aurorahaze',
    light: 'aurorahaze',
    dark: 'chaotichaze'
  },
  arcarumfragment: {
		type: GroupType.summon,
    2040236: 'bellatorfragment',
    2040237: 'aquilafragment',
    2040238: 'celsusfragment',
    2040239: 'celsusfragment',
    2040240: 'aquilafragment',
    2040241: 'celsusfragment',
    2040242: 'celsusfragment',
    2040243: 'bellatorfragment',
    2040244: 'aquilafragment',
    2040245: 'bellatorfragment',    
  },
  arcarumssr5treasure: {
		type: GroupType.summon,
    2040236: 'toxictulip',
    2040237: 'bestiafruit',
    2040238: 'jumbobeastbone',
    2040239: 'klugerherb',
    2040240: 'rhempepper',
    2040241: 'brokenteacup',
    2040242: 'rustyeave',
    2040243: 'translucentsilk',
    2040244: 'meditativesutra',
    2040245: 'dustybook'
  },
  // Anima
  anima: {
		type: GroupType.element,
    fire: 'animafire',
    water: 'animawater',
    earth: 'animaearth',
    wind: 'animawind',
    light: 'animalight',
    dark: 'animadark'
  },
  omegaanima: {
		type: GroupType.element,
    fire: 'fireomegaanima',
    water: 'wateromegaanima',
    earth: 'earthomegaanima',
    wind: 'windomegaanima',
    light: 'lightomegaanima',
    dark: 'darkomegaanima'
  },
  omegaunique: {
		type: GroupType.element,
    fire: 'omegauniquefire',
    water: 'omegauniquewater',
    earth: 'omegauniqueearth',
    wind: 'omegauniquewind',
    light: 'omegauniquelight',
    dark: 'omegauniquedark'
  },
  omega2omegaanima: {
		type: GroupType.element,
    fire: 'fireomega2omegaanima',
    water: 'wateromega2omegaanima',
    earth: 'earthomega2omegaanima',
    wind: 'windomega2omegaanima',
    light: 'lightomega2omegaanima',
    dark: 'darkomega2omegaanima'
  },
  enneadomegaanima: {
		type: GroupType.element,
    fire: 'fireenneadomegaanima',
    water: 'waterenneadomegaanima',
    earth: 'earthenneadomegaanima',
    wind: 'windenneadomegaanima',
    light: 'lightenneadomegaanima',
    dark: 'darkenneadomegaanima'
  },
  omega3omegaanima: {
		type: GroupType.element,
    fire: 'fireomega3omegaanima',
    water: 'wateromega3omegaanima',
    earth: 'earthomega3omegaanima',
    wind: 'windomega3omegaanima',
    light: 'lightomega3omegaanima',
    dark: 'darkomega3omegaanima'
  },
  sixdragon: {
		type: GroupType.element,
    fire: 'firesixdragon',
    water: 'watersixdragon',
    earth: 'earthsixdragon',
    wind: 'windsixdragon',
    light: 'lightsixdragon',
    dark: 'darksixdragon'
  },
  sixdragonjewel: {
		type: GroupType.element,
    fire: 'firesixdragonjewel',
    water: 'watersixdragonjewel',
    earth: 'earthsixdragonjewel',
    wind: 'windsixdragonjewel',
    light: 'lightsixdragonjewel',
    dark: 'darksixdragonjewel'
  },
  t1anima: {
		type: GroupType.element,
    fire: 'firet1anima',
    water: 'watert1anima',
    earth: 'eartht1anima',
    wind: 'windt1anima',
    light: 'lightt1anima',
    dark: 'darkt1anima'
  },
  t2anima: {
		type: GroupType.element,
    fire: 'firet2anima',
    water: 'watert2anima',
    earth: 'eartht2anima',
    wind: 'windt2anima',
    light: 'lightt2anima',
    dark: 'darkt2anima'
  },
  primarchanima: {
    type: GroupType.element,
    fire: 'michaelanima',
    water: 'gabrielanima',
    earth: 'urielanima',
    wind: 'raphaelanima',
    light: ['michaelanima', 'raphaelanima'],
    dark: ['gabrielanima', 'urielanima']
  },
  halos: {
    type: GroupType.element,
    fire: 'halofire',
    water: 'halowater',
    earth: 'haloearth',
    wind: 'halowind',
    light: ['halofire', 'halowind'],
    dark: ['halowater', 'haloearth']
  },
  beastsomegaanima: {
    type: GroupType.element,
    fire: 'huanglongomegaanima',
    water: 'qilinomegaanima',
    earth: 'qilinomegaanima',
    wind: 'huanglongomegaanima',
    light: 'huanglongomegaanima',
    dark: 'qilinomegaanima'
  }
});

export default {
  items,
  groups,
}